export const LOGIN = 'LOGIN';
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const GET_ALL_STUDENT = 'GET_ALL_STUDENT';
export const SET_ALL_STUDENT = 'SET_ALL_STUDENT';
export const FETCH_PAYMENT = 'FETCH_PAYMENT';
export const SET_PAYMENT_RESPONSE = 'SET_PAYMENT_RESPONSE';
export const FETCH_CERTIFICATE = 'FETCH_CERTIFICATE';
export const SET_CERTIFICATE = 'SET_CERTIFICATE';