export const LOGIN = 'LOGIN';
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const GET_ALL_STUDENT = 'GET_ALL_STUDENT';
export const SET_ALL_STUDENT = 'SET_ALL_STUDENT';
export const FETCH_PAYMENT = 'FETCH_PAYMENT';
export const SET_PAYMENT_RESPONSE = 'SET_PAYMENT_RESPONSE';
export const FETCH_CERTIFICATE = 'FETCH_CERTIFICATE';
export const SET_CERTIFICATE = 'SET_CERTIFICATE';
export const FETCH_TEACHER = 'FETCH_TEACHER';
export const SET_TEACHER = 'SET_TEACHER';
export const ADD_TEACHER = 'ADD_TEACHER';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';
export const SET_REMOVE_TEACHER = 'SET_REMOVE_TEACHER';
export const FETCH_GALLERY = 'FETCH_GALLERY';
export const SET_GALLERY = 'SET_GALLERY';
export const CREATE_GALLERY = 'CREATE_GALLERY';
export const REMOVE_GALLERY = 'REMOVE_GALLERY';
export const SET_REMOVE_GALLERY = 'SET_REMOVE_GALLERY';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const SET_ARTICLE = 'SET_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const SET_REMOVE_ARTICLE = 'SET_REMOVE_ARTICLE';
export const UPDATE_PAYMENT_STATUS = 'UPDATE_PAYMENT_STATUS';
export const SET_PAYMENT_STATUS = 'SET_PAYMENT_STATUS';
export const FETCH_TESTIMONY = 'FETCH_TESTIMONY';
export const SET_TESTIMONY = 'SET_TESTIMONY';
export const REMOVE_TESTIMONY = 'REMOVE_TESTIMONY';
export const SET_REMOVE_TESTIMONY = 'SET_REMOVE_TESTIMONY';
export const REMOVE_PAYMENT = 'REMOVE_PAYMENT';
export const SET_REMOVE_PAYMENT = 'SET_REMOVE_PAYMENT';
export const FETCH_ASSESSMENT = 'FETCH_ASSESSMENT';
export const SET_ASSESSMENT = 'SET_ASSESSMENT';
export const REMOVE_ASSESSMENT = 'REMOVE_ASSESSMENT';
export const SET_REMOVE_ASSESSMENT = 'SET_REMOVE_ASSESSMENT';
export const REMOVE_CERTIFICATE = 'REMOVE_CERTIFICATE';
export const SET_REMOVE_CERTIFICATE = 'SET_REMOVE_CERTIFICATE';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const SET_REMOVE_STUDENT = 'SET_REMOVE_STUDENT';





